version: "3.8"
services:
  nats:
    image: nats:2.9
    ports:
      - "4222:4222"
    networks:
      - app-network
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "80:80"
    depends_on:
      - frontend
      - transcription-agent
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped

  transcription-agent:
    build:
      context: ./services/transcription-agent
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - nats
    networks:
      - app-network
    volumes:
      - ./storage/recordings:/app/storage/recordings
      - ./storage/transcriptions:/app/storage/transcriptions
    restart: unless-stopped

networks:
  app-network:
    driver: bridge